input {
  file {
    path => "/opt/ctf-logs-src/*.json"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json_lines
    mode => "read"
    ecs_compatibility => "disabled"
  }
}

filter {
  date {
    match => ["@timestamp", "ISO8601"]
    target => "@timestamp"
  }

  mutate {
    add_field => {
      "environment"  => "corp.local"
      "domain"       => "CORP"
      "ctf_scenario" => "DFIR-Incident-2024-03-15"
    }
  }

  # Mapping hôte → IP
  if [host] == "WIN-ACCT01" {
    mutate { add_field => { "host_ip" => "192.168.10.45" } }
  }
  if [host] == "APP-SRV01" {
    mutate { add_field => { "host_ip" => "192.168.10.52" } }
  }
  if [host] == "DC01" {
    mutate { add_field => { "host_ip" => "192.168.10.10" } }
  }
}

output {
  elasticsearch {
    hosts              => ["http://localhost:9200"]
    index              => "dfir-incident-%{+YYYY.MM.dd}"
    action             => "index"
    ilm_enabled        => false
    ecs_compatibility  => "disabled"
  }
}
