[Definition]
# Grafana logfmt : échec d'authentification = POST /login avec status=401
failregex = ^.*msg="Request Completed".*path=/login\s+status=401\s+remote_addr=<HOST>\s.*$
ignoreregex =
journalmatch = _SYSTEMD_UNIT=grafana-server.service
