- name: Recharger le pare-feu
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted

- name: Redémarrer netbird
  ansible.builtin.service:
    name: netbird
    state: restarted
