[DEFAULT]
maxretry = 3
findtime = 10m
bantime  = 1d
ignoreip = 127.0.0.1/8 ::1
backend  = systemd

[sshd]
enabled = true
port    = 22
filter  = sshd

[ctfd]
enabled = true
filter = ctfd
backend = systemd
journalmatch = _SYSTEMD_UNIT=ctfd.service
maxretry = 3
findtime = 10m
bantime = 1d

[mysqld-auth]
enabled = true
port    = 3306
filter  = mysqld-auth
backend = systemd

[recidive]
enabled  = true
filter   = recidive
logpath  = /var/log/fail2ban.log
banaction = iptables-allports
findtime = 1d
maxretry = 2
bantime  = -1
